### PR TITLE
got bored here is some improved sprites i might do turrets and units later

### PR DESCRIPTION
**Pull request by Otamamori917**

### CODE REVIEW

**Comment by Otamamori917** [comment]
ai-core
ai-core-fabricator
molten-alloy-forge
pyra-factory

**Review by valigaming15 — APPROVED** [review]
These sprites look awesome!

**Comment by Otamamori917** [comment]
I'll start working on turret in a bit 
IL also make animation for em

**Comment by Otamamori917** [comment]
I'm going to treat fossores, arel, navis, and mothership are a tech tree so there will be sprites similar I'll also be changing up arel weapon so it isn't a copy of a sterna

**Pull request merged**
