### PR TITLE
Flux, Prisma, and Sanitatem Sprites and turret animations and Mass Error fixes

### PR DESCRIPTION
**Pull request by Otamamori917**
### changes
**turrets**
- artillery was renamed to flux and now has new sprite and animation.
flux-preview
- large artillery was renamed to prisma and has new sprite and animation.
prisma-preview
- they both got a slight dmg bonus.
 _due to Flux **(previously artillery)** and Prisma **(previously large artillery)** getting turret animations they now have a delay before they can fire the bonus in dmg should compensate nicely._

- sanitatem's laser color was changed to green and has a new sprite and animation.
sanitatem-preview
**Misc**
 - i went though every script and fixed any errors.
 - i added my name in mod.hjson file labeled as spriter

 ### Unit sprites and turret improvements are next!

### CODE REVIEW

**Comment by Otamamori917** [comment]
ill have to work on units later i suggest don't merge this just yet

**Comment by Otamamori917** [comment]
if you want to test turrets in mod folder (in mindustry) press import mod then from github and type 
**Otamamori917/Prya-Erekir**

**Comment by Otamamori917** [comment]
### Nice.
- image
- lol

**Review by Otamamori917 — COMMENTED** [review]
non check are most likely gonna be changed or tweaked

**Review by valigaming15 — APPROVED** [review]
good job mate :D

**Pull request merged**
